In [2]:
import numpy as np
array=np.array([1,2,3,4,3])
array

array([1, 2, 3, 4, 3])

In [3]:
array.shape

(5,)

In [5]:
array.ndim

1

In [6]:
array.dtype

dtype('int32')

In [11]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[3,8,4]]], dtype='float')
arr

array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[7., 8., 9.],
        [3., 8., 4.]]])

In [12]:
arr.shape


(2, 2, 3)

In [16]:
ran_zeros=np.zeros((5))
ran_zeros

array([0., 0., 0., 0., 0.])

In [17]:
ran_zero=np.zeros((5,8))
ran_zero

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
ran_one=np.ones((0,0))
ran_one

array([], shape=(0, 0), dtype=float64)

In [27]:
ful=np.full((4,5),45)
ful

array([[45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45]])

In [32]:
radm=np.random.random((4,5))
radm

array([[0.37317129, 0.3621904 , 0.12491681, 0.63011458, 0.90414283],
       [0.54116372, 0.44493455, 0.51406518, 0.2745474 , 0.52883387],
       [0.09031449, 0.6049666 , 0.76813825, 0.27417917, 0.95080679],
       [0.45743735, 0.98247965, 0.75603795, 0.86715312, 0.95914789]])

In [36]:
x=np.array([1,2,3,np.nan,5, np.inf])
x

array([ 1.,  2.,  3., nan,  5., inf])

In [38]:
for i  in x:
    print(f'Is the value nan {i}: {np.isnan(i)}')
    print(f'Is the value nan {i}: {i==np.inf}')
    print(f'Is the value nan {i}: {i==np.nan}')

Is the value nan 1.0: False
Is the value nan 1.0: False
Is the value nan 1.0: False
Is the value nan 2.0: False
Is the value nan 2.0: False
Is the value nan 2.0: False
Is the value nan 3.0: False
Is the value nan 3.0: False
Is the value nan 3.0: False
Is the value nan nan: True
Is the value nan nan: False
Is the value nan nan: False
Is the value nan 5.0: False
Is the value nan 5.0: False
Is the value nan 5.0: False
Is the value nan inf: False
Is the value nan inf: True
Is the value nan inf: False


In [41]:
varieties= np.array([['pelu','maris','funmi'],['love','excess','brother'],['lady', 'man' , 'women']])
print(varieties)

[['pelu' 'maris' 'funmi']
 ['love' 'excess' 'brother']
 ['lady' 'man' 'women']]


In [42]:
varieties[0][1]

'maris'

In [43]:
varieties[0][1][3]

'i'

In [44]:
new=varieties

In [45]:
new[1][2]=np.nan

In [46]:
varieties


array([['pelu', 'maris', 'funmi'],
       ['love', 'excess', 'nan'],
       ['lady', 'man', 'women']], dtype='<U7')

In [47]:
new

array([['pelu', 'maris', 'funmi'],
       ['love', 'excess', 'nan'],
       ['lady', 'man', 'women']], dtype='<U7')

In [48]:
cop=new.copy()

In [49]:
cop[1][2]=np.inf

In [51]:
print(new)
cop

[['pelu' 'maris' 'funmi']
 ['love' 'excess' 'nan']
 ['lady' 'man' 'women']]


array([['pelu', 'maris', 'funmi'],
       ['love', 'excess', 'inf'],
       ['lady', 'man', 'women']], dtype='<U7')