### Arithmetic & Linear Algebra

In [3]:
import numpy as np

### Array Oprations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,6]])

print(f"arr1 => {arr1}")
print(f"arr2 => {arr2}")

arr1 => [1 2 3 4 5]
arr2 => [[1 2 3]
 [4 5 6]]


In [5]:
print(f"arr1 shape => {arr1.shape}")
print(f"arr2 shape => {arr2.shape}")

arr1 shape => (5,)
arr2 shape => (2, 3)


In [6]:
print(f"arr1 dim => {arr1.ndim}")
print(f"arr2 dim => {arr2.ndim}")

arr1 dim => 1
arr2 dim => 2


In [7]:
arr1 + 10 # this adds the elements of array1 by 10

array([11, 12, 13, 14, 15])

In [8]:
arr1 * 10 # this multiplies the elements of array1 by 10

array([10, 20, 30, 40, 50])

In [9]:
dot_arrys = np.dot(arr2, np.array([2,3,4]))
dot_arrys

array([20, 47])

In [10]:
arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])
# a0 * b0 + a1 * b1 + a2 * b2 == 4 + 10 + 18 = 32

Dot product of arrays a & b: 32


In [15]:
# 2D dot operation
matrix_a = np.array([[1,2],[3,4]])
matrix_b = np.array([[5,6],[7,8]])
prod_matrix = np.dot(matrix_a, matrix_b)
print(f"Dot product of matrices a & b: {prod_matrix}")

Dot product of matrices a & b: [[19 22]
 [43 50]]


In [13]:
matrix_a # formula for result: (1.5 + 2.7) (1.6 + 2.8), (3.5 + 4.7), (3.6 + 4.8)

array([[1, 2],
       [3, 4]])

In [14]:
matrix_b

array([[5, 6],
       [7, 8]])

In [16]:
prod_matrix

array([[19, 22],
       [43, 50]])

In [21]:
tensor_a = np.random.random((3,3))
tensor_a

array([[0.7912338 , 0.85194021, 0.84788929],
       [0.8228989 , 0.65671725, 0.23525529],
       [0.31541806, 0.02538286, 0.52763065]])

In [18]:
tensor_a.shape

(3, 3)

In [22]:
# transpose the matrix
arr_transpose = np.transpose(tensor_a)
arr_transpose

array([[0.7912338 , 0.8228989 , 0.31541806],
       [0.85194021, 0.65671725, 0.02538286],
       [0.84788929, 0.23525529, 0.52763065]])

### Broadcasting 

In [23]:
# Broadcasting allows operations to be performed on arrays of different shapes and sizes

arry1 = np.array([1,2,3,4,5])
arry2 = np.array([110])

arry2

array([110])

In [24]:
arry2.shape

(1,)

In [26]:
arry1.shape

(5,)

In [27]:
print(f"arry1 size => {arry1.size}")
print(f"arry2 size => {arry2.size}")

arry1 size => 5
arry2 size => 1


In [29]:
result_arry = arry1 + arry2
result_arry # here's a scalar addition

array([111, 112, 113, 114, 115])

In [30]:
# broadcasting with 2d arrays
matrix1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
matrix2 = np.array([110, 120, 130, 140, 150])

matrix1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
matrix1.size

10

In [32]:
matrix1.shape

(2, 5)

In [33]:
matrix1.ndim

2

In [34]:
matrix2.size

5

In [35]:
matrix2.shape

(5,)

In [36]:
matrix2.ndim

1

In [37]:
matrix_addn = matrix1 + matrix2
matrix_addn

array([[111, 122, 133, 144, 155],
       [116, 127, 138, 149, 160]])

In [38]:
test_matrix = np.array([110, 120, 130, 140])
test_matrix

array([110, 120, 130, 140])

In [39]:
test_matrix.size

4

In [40]:
test_matrix.shape

(4,)

In [41]:
matrix_test_addn = matrix1 + test_matrix
matrix_test_addn # this obeys the mathematical law fatai mentioned. 

ValueError: operands could not be broadcast together with shapes (2,5) (4,) 

### NP Aggregation Functions

In [42]:
test_matrix

array([110, 120, 130, 140])

In [43]:
sum_test_matrix = np.sum(test_matrix)
sum_test_matrix

500

In [44]:
new_test_matrix = test_matrix.copy()
new_test_matrix

array([110, 120, 130, 140])

In [45]:
new_test_matrix[2] = np.nan
new_test_matrix

ValueError: cannot convert float NaN to integer

In [47]:
# convert the existing elements to float
new_test_matrix = np.array(new_test_matrix, dtype=np.float64)
new_test_matrix #dtype of elements has changed from int to float

array([110., 120., 130., 140.])

In [48]:
new_test_matrix[2] = np.nan 
new_test_matrix

array([110., 120.,  nan, 140.])

In [50]:
# using the insert mtd to add new values to the array
# the syntax is: np.insert(array, 2, new_val) where new_value is np.nan
new_test_matrix = np.insert(new_test_matrix, 1, np.nan)
new_test_matrix

array([110.,  nan, 120.,  nan, 140.])

In [51]:
sum_new_test_matrix = np.sum(new_test_matrix)
sum_new_test_matrix

nan

In [52]:
sum_new_test_matrix

nan

In [53]:
new_test_matrix

array([110.,  nan, 120.,  nan, 140.])

In [54]:
nansum_new_test_matrix = np.nansum(new_test_matrix)
nansum_new_test_matrix

370.0

In [55]:
test_matrix

array([110, 120, 130, 140])

In [56]:
# get mean of the elements
np.mean(test_matrix)

125.0

In [57]:
# get the median of the elements
np.median(test_matrix)

125.0

In [58]:
np.mode(test_matrix) # there's no mode mtd yet! (as at nov, 2023) 

AttributeError: module 'numpy' has no attribute 'mode'

In [59]:
test_matrix = np.insert(test_matrix, 3, 110)
test_matrix

array([110, 120, 130, 110, 140])

In [60]:
np.mode(test_matrix)

AttributeError: module 'numpy' has no attribute 'mode'

In [61]:
np.median(test_matrix)

120.0

In [62]:
np.mean(test_matrix)

122.0

### Handling Files

In [67]:
file = '/Users/damilare/Documents/ingryd/datasets/nba.csv'
imdb_top_1000.csv
file

'/Users/damilare/Documents/ingryd/datasets/nba.csv'

In [68]:
data = np.genfromtxt(file, delimiter=',')
data

array([[         nan,          nan,          nan, ...,          nan,
                 nan,          nan],
       [         nan,          nan, 0.000000e+00, ..., 1.800000e+02,
                 nan, 7.730337e+06],
       [         nan,          nan, 9.900000e+01, ..., 2.350000e+02,
                 nan, 6.796117e+06],
       ...,
       [         nan,          nan, 2.100000e+01, ..., 2.560000e+02,
                 nan, 2.900000e+06],
       [         nan,          nan, 2.400000e+01, ..., 2.310000e+02,
                 nan, 9.472760e+05],
       [         nan,          nan,          nan, ...,          nan,
                 nan,          nan]])

In [71]:
data = [i for i in data]
data

[array([nan, nan, nan, nan, nan, nan, nan, nan, nan]),
 array([         nan,          nan, 0.000000e+00,          nan,
        2.500000e+01,          nan, 1.800000e+02,          nan,
        7.730337e+06]),
 array([         nan,          nan, 9.900000e+01,          nan,
        2.500000e+01,          nan, 2.350000e+02,          nan,
        6.796117e+06]),
 array([ nan,  nan,  30.,  nan,  27.,  nan, 205.,  nan,  nan]),
 array([        nan,         nan, 2.80000e+01,         nan, 2.20000e+01,
                nan, 1.85000e+02,         nan, 1.14864e+06]),
 array([     nan,      nan, 8.00e+00,      nan, 2.90e+01,      nan,
        2.31e+02,      nan, 5.00e+06]),
 array([    nan,     nan, 9.0e+01,     nan, 2.9e+01,     nan, 2.4e+02,
            nan, 1.2e+07]),
 array([        nan,         nan, 5.50000e+01,         nan, 2.10000e+01,
                nan, 2.35000e+02,         nan, 1.17096e+06]),
 array([        nan,         nan, 4.10000e+01,         nan, 2.50000e+01,
                nan, 2.3800

In [73]:
data[1]

array([         nan,          nan, 0.000000e+00,          nan,
       2.500000e+01,          nan, 1.800000e+02,          nan,
       7.730337e+06])

In [91]:
import json
import csv

new_file = '/Users/damilare/Documents/ingryd/datasets/imdb_top_1000.csv'

#data = np.genfromtxt(new_file, delimiter)
#data

with open(new_file, 'r') as csv_file:
    csv_reader = csv.reader(csv_file)
    
    data_list = list(csv_reader)
    
    #header = next(csv_reader)
    #print(f"Headers: {header}")
    
    data = [i for i in data_list]
    print(data)
    

[['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate', 'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director', 'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'], ['https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX67_CR0,0,67,98_AL_.jpg', 'The Shawshank Redemption', '1994', 'A', '142 min', 'Drama', '9.3', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', '80', 'Frank Darabont', 'Tim Robbins', 'Morgan Freeman', 'Bob Gunton', 'William Sadler', '2343110', '28,341,469'], ['https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UY98_CR1,0,67,98_AL_.jpg', 'The Godfather', '1972', 'A', '175 min', 'Crime, Drama', '9.2', "An organized crime dynasty's aging patriarch transfers control of his clandestine empire to his reluctant son.", '100', 'Francis Fo

In [92]:
data[0]

['Poster_Link',
 'Series_Title',
 'Released_Year',
 'Certificate',
 'Runtime',
 'Genre',
 'IMDB_Rating',
 'Overview',
 'Meta_score',
 'Director',
 'Star1',
 'Star2',
 'Star3',
 'Star4',
 'No_of_Votes',
 'Gross']

In [93]:
data[1]

['https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX67_CR0,0,67,98_AL_.jpg',
 'The Shawshank Redemption',
 '1994',
 'A',
 '142 min',
 'Drama',
 '9.3',
 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
 '80',
 'Frank Darabont',
 'Tim Robbins',
 'Morgan Freeman',
 'Bob Gunton',
 'William Sadler',
 '2343110',
 '28,341,469']

In [94]:
new_data = dict(data_list)
new_data

ValueError: dictionary update sequence element #0 has length 16; 2 is required

In [96]:
# reading it using the DictReader mtd

with open(new_file, 'r') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    
    data_list = list(csv_reader)
    print(data_list)

[{'Poster_Link': 'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX67_CR0,0,67,98_AL_.jpg', 'Series_Title': 'The Shawshank Redemption', 'Released_Year': '1994', 'Certificate': 'A', 'Runtime': '142 min', 'Genre': 'Drama', 'IMDB_Rating': '9.3', 'Overview': 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'Meta_score': '80', 'Director': 'Frank Darabont', 'Star1': 'Tim Robbins', 'Star2': 'Morgan Freeman', 'Star3': 'Bob Gunton', 'Star4': 'William Sadler', 'No_of_Votes': '2343110', 'Gross': '28,341,469'}, {'Poster_Link': 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UY98_CR1,0,67,98_AL_.jpg', 'Series_Title': 'The Godfather', 'Released_Year': '1972', 'Certificate': 'A', 'Runtime': '175 min', 'Genre': 'Crime, Drama', 'IMDB_Rating': '9.2', 'Overview': "An organized crime dyna

In [97]:
data_list[0]

{'Poster_Link': 'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX67_CR0,0,67,98_AL_.jpg',
 'Series_Title': 'The Shawshank Redemption',
 'Released_Year': '1994',
 'Certificate': 'A',
 'Runtime': '142 min',
 'Genre': 'Drama',
 'IMDB_Rating': '9.3',
 'Overview': 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
 'Meta_score': '80',
 'Director': 'Frank Darabont',
 'Star1': 'Tim Robbins',
 'Star2': 'Morgan Freeman',
 'Star3': 'Bob Gunton',
 'Star4': 'William Sadler',
 'No_of_Votes': '2343110',
 'Gross': '28,341,469'}

In [98]:
len(data_list)

1000

In [99]:
data_list[0]['IMDB_Rating']

'9.3'

## Simple Analysis to Perform on the Dataset

### Get Avg IMDB_Rating

In [100]:
# get all IMDB_Ratings here
imdb_ratings = []

# read file
with open(new_file, 'r') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    for row in csv_reader:
        # append values. of imdb_rating to the list
        imdb_ratings.append(float(row['IMDB_Rating']))
        
    
print(imdb_ratings)

[9.3, 9.2, 9.0, 9.0, 9.0, 8.9, 8.9, 8.9, 8.8, 8.8, 8.8, 8.8, 8.8, 8.7, 8.7, 8.7, 8.7, 8.7, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.1, 8.1, 8.1, 8.1, 8.1,

In [101]:
# convert the list to a np array
imdb_ratings_array = np.array(imdb_ratings)
imdb_ratings_array

array([9.3, 9.2, 9. , 9. , 9. , 8.9, 8.9, 8.9, 8.8, 8.8, 8.8, 8.8, 8.8,
       8.7, 8.7, 8.7, 8.7, 8.7, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6,
       8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5,
       8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5,
       8.5, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4,
       8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.4,
       8.4, 8.4, 8.4, 8.4, 8.4, 8.4, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3,
       8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3,
       8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3,
       8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.2, 8.2,
       8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2,
       8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2,
       8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2,
       8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.2, 8.

In [102]:
type(imdb_ratings)

list

In [103]:
imdb_ratings_array.dtype

dtype('float64')

In [104]:
type(imdb_ratings_array)

numpy.ndarray

In [107]:
# calc the mean of all the movie ratings
avg_imdb_ratings = np.mean(imdb_ratings_array)
print(f"The mean of all {len(imdb_ratings_array)} movies' imdb_ratings is {round(avg_imdb_ratings, 2)}")

The mean of all 1000 movies' imdb_ratings is 7.95


### Get the Genre Distribution

In [108]:
# create a list to save all movie genres
movie_genres = []

# read file
with open(new_file, 'r') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    for row in csv_reader:
        # append values. of genre to the genre list
        movie_genres.append(row['Genre'])
        
movie_genres

['Drama',
 'Crime, Drama',
 'Action, Crime, Drama',
 'Crime, Drama',
 'Crime, Drama',
 'Action, Adventure, Drama',
 'Crime, Drama',
 'Biography, Drama, History',
 'Action, Adventure, Sci-Fi',
 'Drama',
 'Action, Adventure, Drama',
 'Drama, Romance',
 'Western',
 'Action, Adventure, Drama',
 'Action, Sci-Fi',
 'Biography, Crime, Drama',
 'Action, Adventure, Fantasy',
 'Drama',
 'Biography, Drama, History',
 'Comedy, Drama, Thriller',
 'Drama',
 'Adventure, Drama, Sci-Fi',
 'Crime, Drama',
 'Animation, Adventure, Family',
 'Drama, War',
 'Crime, Drama, Fantasy',
 'Comedy, Drama, Romance',
 'Crime, Drama, Mystery',
 'Crime, Drama, Thriller',
 'Action, Adventure, Fantasy',
 'Action, Drama, Mystery',
 'Action, Adventure, Drama',
 'Drama, Family, Fantasy',
 'Crime, Drama, Thriller',
 'Drama, Music',
 'Biography, Comedy, Drama',
 'Drama, Mystery, Sci-Fi',
 'Crime, Drama, Thriller',
 'Biography, Drama, Music',
 'Action, Adventure, Drama',
 'Drama',
 'Crime, Mystery, Thriller',
 'Action, Crime,

In [111]:
# the np.unique() mtd; this flattens an array and returns all unique values in it.

# count the occurence of each genre
unique_genres, genre_counts = np.unique(movie_genres, return_counts=True)

unique_genres

array(['Action, Adventure', 'Action, Adventure, Biography',
       'Action, Adventure, Comedy', 'Action, Adventure, Crime',
       'Action, Adventure, Drama', 'Action, Adventure, Family',
       'Action, Adventure, Fantasy', 'Action, Adventure, History',
       'Action, Adventure, Horror', 'Action, Adventure, Mystery',
       'Action, Adventure, Romance', 'Action, Adventure, Sci-Fi',
       'Action, Adventure, Thriller', 'Action, Adventure, War',
       'Action, Adventure, Western', 'Action, Biography, Crime',
       'Action, Biography, Drama', 'Action, Comedy, Crime',
       'Action, Comedy, Fantasy', 'Action, Comedy, Mystery',
       'Action, Comedy, Romance', 'Action, Crime, Comedy',
       'Action, Crime, Drama', 'Action, Crime, Mystery',
       'Action, Crime, Thriller', 'Action, Drama',
       'Action, Drama, History', 'Action, Drama, Mystery',
       'Action, Drama, Sci-Fi', 'Action, Drama, Sport',
       'Action, Drama, Thriller', 'Action, Drama, War',
       'Action, Drama, We

In [112]:
len(unique_genres) # so we see that there are 202 unique set of movie genres

202

In [113]:
# create a dict to map the unique genres and their total count
genre_distribution = dict(zip(unique_genres, genre_counts))
print(f"Movie Genre Distribution: \n {genre_distribution}")

Movie Genre Distribution: 
 {'Action, Adventure': 5, 'Action, Adventure, Biography': 1, 'Action, Adventure, Comedy': 10, 'Action, Adventure, Crime': 1, 'Action, Adventure, Drama': 14, 'Action, Adventure, Family': 1, 'Action, Adventure, Fantasy': 6, 'Action, Adventure, History': 1, 'Action, Adventure, Horror': 1, 'Action, Adventure, Mystery': 1, 'Action, Adventure, Romance': 1, 'Action, Adventure, Sci-Fi': 21, 'Action, Adventure, Thriller': 5, 'Action, Adventure, War': 2, 'Action, Adventure, Western': 2, 'Action, Biography, Crime': 3, 'Action, Biography, Drama': 7, 'Action, Comedy, Crime': 6, 'Action, Comedy, Fantasy': 3, 'Action, Comedy, Mystery': 1, 'Action, Comedy, Romance': 2, 'Action, Crime, Comedy': 1, 'Action, Crime, Drama': 30, 'Action, Crime, Mystery': 1, 'Action, Crime, Thriller': 10, 'Action, Drama': 5, 'Action, Drama, History': 3, 'Action, Drama, Mystery': 5, 'Action, Drama, Sci-Fi': 2, 'Action, Drama, Sport': 1, 'Action, Drama, Thriller': 4, 'Action, Drama, War': 3, 'Action

### Covid 19 Dataset Mini-EDA

In [117]:
file = '/Users/damilare/Documents/ingryd/datasets/owid-covid-codebook.csv.csv'

# read the file
with open(file, 'r') as covid_file:
    csv_reader = csv.DictReader(covid_file)
    
    # extract info from file
    for row in csv_reader:
        data = row
        print(data)

{'column': 'iso_code', 'source': 'International Organization for Standardization', 'category': 'Others', 'description': "ISO 3166-1 alpha-3 – three-letter country codes. Note that OWID-defined regions (e.g. continents like 'Europe') contain prefix 'OWID_'."}
{'column': 'continent', 'source': 'Our World in Data', 'category': 'Others', 'description': 'Continent of the geographical location'}
{'column': 'location', 'source': 'Our World in Data', 'category': 'Others', 'description': 'Geographical location'}
{'column': 'date', 'source': 'Our World in Data', 'category': 'Others', 'description': 'Date of observation'}
{'column': 'total_cases', 'source': 'COVID-19 Dashboard by the WHO', 'category': 'Confirmed cases', 'description': 'Total confirmed cases of COVID-19. Counts can include probable cases, where reported.'}
{'column': 'new_cases', 'source': 'COVID-19 Dashboard by the WHO', 'category': 'Confirmed cases', 'description': 'New confirmed cases of COVID-19. Counts can include probable ca

In [116]:
data

{'column': 'excess_mortality_cumulative_per_million',
 'source': 'Human Mortality Database (2021), World Mortality Dataset (2021)',
 'category': 'Excess mortality',
 'description': 'Cumulative difference between the reported number of deaths since 1 January 2020 and the projected number of deaths for the same period based on previous years, per million people. For more information, see https://github.com/owid/covid-19-data/tree/master/public/data/excess_mortality'}

In [118]:
### Be on the Lookout for the Assignment