In [1]:
import numpy as np

a = np.full((4,5,5),20)
a

array([[[20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20]],

       [[20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20]],

       [[20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20]],

       [[20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20]]])

In [2]:
a.ndim

3

In [4]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
arr1 = np.zeros(6)
arr1 # this is a vector

array([0., 0., 0., 0., 0., 0.])

In [20]:
arr2 = np.random.randn((3))
arr2

array([ 0.93863919,  0.5694029 , -0.75817283])

In [18]:
arry3 = np.random.random((3, 3))
arry3 # this is a matrix

array([[0.53549025, 0.44640519, 0.46577415],
       [0.54395889, 0.03599633, 0.47180149],
       [0.25104807, 0.86789006, 0.55288054]])

In [21]:
arry3.size

9

In [22]:
arr2.size

3

In [23]:
arr2.ndim

1

#### NB


- Arrays of 1 dim are vectors
- Arrays of 2 dim are matrix
- Arrays of 3 dim are tensor

### Working With Special Values

In [25]:
x = 0/0
x

ZeroDivisionError: division by zero

In [26]:
# two special values we'll be dealing with are nan & inf
# NaN refers to a missing info or an undefined number.
# inf refers to infinity
# Nothing is equal to NaN, however something can be equivalent to NaN

vec1 = np.array([1,-1,0], dtype=np.float16)
vec1

array([ 1., -1.,  0.], dtype=float16)

In [27]:
# access the value of vec1
vec1[0]

1.0

In [28]:
vec2 = vec1 / 0 # divide vec1 by 0
vec2

/var/folders/4r/3_6gh8rj44g43v_wlyprm7h40000gn/T/ipykernel_14216/682713793.py:1: RuntimeWarning: divide by zero encountered in divide
  vec2 = vec1 / 0 # divide vec1 by 0
/var/folders/4r/3_6gh8rj44g43v_wlyprm7h40000gn/T/ipykernel_14216/682713793.py:1: RuntimeWarning: invalid value encountered in divide
  vec2 = vec1 / 0 # divide vec1 by 0


array([ inf, -inf,  nan], dtype=float16)

In [29]:
# Detecting the special values

for i in vec2:
    print(f"Number to evaluate: {i}")
    print("########")
    print(f"Inf: {str(i == np.inf)}")
    print(f"Neg Inf: {str(i == -np.inf)}")
    print(f"NaN: {str(i == np.nan)}") # this is wrong!!!
    print()

Number to evaluate: inf
########
Inf: True
Neg Inf: False
NaN: False

Number to evaluate: -inf
########
Inf: False
Neg Inf: True
NaN: False

Number to evaluate: nan
########
Inf: False
Neg Inf: False
NaN: False



In [30]:
# Nothing is equal to NaN, however something can be Equivalent to NaN

x = ''
x

''

In [33]:
y == ''
y

NameError: name 'y' is not defined

In [37]:
type(y)

NameError: name 'y' is not defined

In [38]:
a = 3
b == a
b == 33

a

3

In [39]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [40]:
a == 3

True

In [41]:
c = 6 - 3
a == c

True

In [42]:
nan = 1

nan

1

In [43]:
h = 'nothing'
i = 'something'

h = nan
i == nan

False

In [44]:
for i in vec2:
    print(f"Number to evaluate: {i}")
    print("########")
    print(f"Inf: {str(i == np.inf)}")
    print(f"Neg Inf: {str(i == -np.inf)}")
    print(f"NaN: {str(np.isnan(i))}") # this is correct syntax
    print()

Number to evaluate: inf
########
Inf: True
Neg Inf: False
NaN: False

Number to evaluate: -inf
########
Inf: False
Neg Inf: True
NaN: False

Number to evaluate: nan
########
Inf: False
Neg Inf: False
NaN: True



In [45]:
# detect infinite values 
for i in vec2:
    print(f"Number to evaluate: {i}")
    print("########")
    print(f"Is Finite Value: {str(np.isfinite(i))}") # checks if i is a finite value
    print(f"Is Infinite Value: {str(np.isinf(i))}") # checks if i is an infinite value 
    print()

Number to evaluate: inf
########
Is Finite Value: False
Is Infinite Value: True

Number to evaluate: -inf
########
Is Finite Value: False
Is Infinite Value: True

Number to evaluate: nan
########
Is Finite Value: False
Is Infinite Value: False



In [46]:
vec2[0]

inf

In [47]:
vec2[1]

-inf

In [48]:
vec2[2]

nan

In [49]:
5 ** vec2[0]

inf

In [50]:
5 ** vec2[1]

0.0

In [51]:
5 ** vec2[2]

nan

In [55]:
vec3 = np.array([9999], dtype='float')
vec3

array([9999.])

In [56]:
vec3[0]

9999.0

In [57]:
vec3[0] ** vec3[0] # we have an infinite value cos the program is very very large 

/var/folders/4r/3_6gh8rj44g43v_wlyprm7h40000gn/T/ipykernel_14216/3555918632.py:1: RuntimeWarning: overflow encountered in double_scalars
  vec3[0] ** vec3[0]


inf

In [58]:
a = 9999
a ** a

ValueError: Exceeds the limit (4300) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit

In [59]:
vec4 = np.ones(7)
vec4

array([1., 1., 1., 1., 1., 1., 1.])

In [60]:
vec4.dtype

dtype('float64')

In [63]:
vec4.dtype = 'int64' # or vec4.dtype = int ; this is a wrong way of casting/converting 
# your np data types. you'll have garbage values i.e. random values from memory.
vec4.dtype

dtype('int64')

In [64]:
vec4

array([4607182418800017408, 4607182418800017408, 4607182418800017408,
       4607182418800017408, 4607182418800017408, 4607182418800017408,
       4607182418800017408])

In [65]:
vec4

array([4607182418800017408, 4607182418800017408, 4607182418800017408,
       4607182418800017408, 4607182418800017408, 4607182418800017408,
       4607182418800017408])

In [68]:
vec4 = np.ones(7)
vec4

array([1., 1., 1., 1., 1., 1., 1.])

In [69]:
# this is the right/appropriate way to do it
vec4 = np.array(vec4, dtype='int64')
vec4.dtype

dtype('int64')

In [70]:
vec4

array([1, 1, 1, 1, 1, 1, 1])

In [72]:
# assign a nan to the array
vec4 = np.ones(7)
vec4[1] = np.nan
vec4

array([ 1., nan,  1.,  1.,  1.,  1.,  1.])

In [73]:
np.sum(vec4) # sum everything together

nan

In [74]:
np.nansum(vec4) # this removes the nan then sums the elements 

6.0

In [75]:
str_vec = np.array([['Judge', 'Goat', 'Saudi'], ['Spurs', 'Bottlers', 'Reds']])
str_vec.dtype

dtype('<U8')

In [76]:
str_vec.size

6

In [77]:
str_vec.shape

(2, 3)

In [78]:
str_vec.ndim

2

In [79]:
str_vec

array([['Judge', 'Goat', 'Saudi'],
       ['Spurs', 'Bottlers', 'Reds']], dtype='<U8')

In [80]:
str_vec[1][2]

'Reds'

In [81]:
str_vec[0][1][2]

'a'

In [82]:
str_vec[0]

array(['Judge', 'Goat', 'Saudi'], dtype='<U8')

In [83]:
str_vec[0][1][2][3]

IndexError: string index out of range

In [84]:
# what does the dtype mean and how to work with it?
str_vec

array([['Judge', 'Goat', 'Saudi'],
       ['Spurs', 'Bottlers', 'Reds']], dtype='<U8')

In [85]:
str_vec[0]

array(['Judge', 'Goat', 'Saudi'], dtype='<U8')

In [86]:
str_vec[1]

array(['Spurs', 'Bottlers', 'Reds'], dtype='<U8')

In [87]:
str_vec[0][0]

'Judge'

In [88]:
str_vec[0][0][2]

'd'

In [89]:
str_vec.dtype

dtype('<U8')

In [90]:
str_vec[0][2] =  'Burkinafaso'
str_vec

array([['Judge', 'Goat', 'Burkinaf'],
       ['Spurs', 'Bottlers', 'Reds']], dtype='<U8')

In [91]:
str_vec = np.array(str_vec, dtype='<U16')
str_vec

array([['Judge', 'Goat', 'Burkinaf'],
       ['Spurs', 'Bottlers', 'Reds']], dtype='<U16')

In [92]:
str_vec[0][2] =  'Burkinafaso'
str_vec

array([['Judge', 'Goat', 'Burkinafaso'],
       ['Spurs', 'Bottlers', 'Reds']], dtype='<U16')

In [93]:
str_vec

array([['Judge', 'Goat', 'Burkinafaso'],
       ['Spurs', 'Bottlers', 'Reds']], dtype='<U16')

### Copy the array obj 

In [95]:
# copy the array
new_str_vec = str_vec

In [96]:
new_str_vec

array([['Judge', 'Goat', 'Burkinafaso'],
       ['Spurs', 'Bottlers', 'Reds']], dtype='<U16')

In [97]:
str_vec[0][1] = np.nan
str_vec

array([['Judge', 'nan', 'Burkinafaso'],
       ['Spurs', 'Bottlers', 'Reds']], dtype='<U16')

In [98]:
new_str_vec

array([['Judge', 'nan', 'Burkinafaso'],
       ['Spurs', 'Bottlers', 'Reds']], dtype='<U16')

In [100]:
new_arry = str_vec.copy() # the copy mtd creates a new instance independent of the parent array
new_arry

array([['Judge', 'nan', 'Burkinafaso'],
       ['Spurs', 'Bottlers', 'Reds']], dtype='<U16')

In [101]:
str_vec[1][2] = np.nan
str_vec

array([['Judge', 'nan', 'Burkinafaso'],
       ['Spurs', 'Bottlers', 'nan']], dtype='<U16')

In [102]:
new_arry

array([['Judge', 'nan', 'Burkinafaso'],
       ['Spurs', 'Bottlers', 'Reds']], dtype='<U16')

### Save the array obj

In [105]:
# To save the array obj  
'''
The ffg syntax are used to save an array in np
save(file, arr), saves in a npy format.
savez(file, arr), saves in npz format i.e. a compressed file
savetxt(file, arr, delimeter), saves in a text file or csv file (when using the delimeter arg)
arr.tofile(file, sep), saves in a file with the arr elements separated by comma
'''

file = '/Users/damilare/Documents/ingryd/datasets/numpy_data/new_array.npy'


new_arry

array([['Judge', 'nan', 'Burkinafaso'],
       ['Spurs', 'Bottlers', 'Reds']], dtype='<U16')

In [106]:
np.save(file, new_arry)

In [107]:
# load the array from the npy file in np
get_arry = np.load(file)
get_arry

array([['Judge', 'nan', 'Burkinafaso'],
       ['Spurs', 'Bottlers', 'Reds']], dtype='<U16')

In [109]:
# using the savetxt mtd

# declare file path
file2 = '/Users/damilare/Documents/ingryd/datasets/numpy_data/another_array.csv'


In [117]:
np.savetxt(file2, new_arry, delimiter=",") # separate the values by comma

TypeError: Mismatch between array dtype ('<U16') and format specifier ('%.18e,%.18e,%.18e')

In [113]:
new_arry.ndim

2

In [119]:
new_arry2 = np.random.random((3,4)) # the savetxt mtd works with real numbers and not strings

In [120]:
new_arry2

array([[0.01842995, 0.16727138, 0.52458089, 0.95673066],
       [0.82820891, 0.05670513, 0.59104059, 0.90642109],
       [0.806815  , 0.30562813, 0.15095961, 0.91586111]])

In [121]:
np.savetxt(file2, new_arry2, delimiter=",")

In [122]:
# read the another_array.csv file

get_csv_file = np.load(file2)
get_csv_file

ValueError: Cannot load file containing pickled data when allow_pickle=False

In [123]:
get_csv_file = np.load(file2, allow_pickle=True)
get_csv_file # we can't use the load mtd to open a csv/txt file

UnpicklingError: Failed to interpret file '/Users/damilare/Documents/ingryd/datasets/numpy_data/another_array.csv' as a pickle

In [124]:
# let's use the open func to read the csv file
get_csv_file = open(file2, 'r')
get_csv_file

<_io.TextIOWrapper name='/Users/damilare/Documents/ingryd/datasets/numpy_data/another_array.csv' mode='r' encoding='UTF-8'>

In [125]:
get_csv_file.read()

'1.842995381228673679e-02,1.672713832088749131e-01,5.245808899561253957e-01,9.567306592828144218e-01\n8.282089075405481005e-01,5.670513082269779126e-02,5.910405949723169794e-01,9.064210937126564449e-01\n8.068149984836069377e-01,3.056281348720055746e-01,1.509596063551595924e-01,9.158611103135182452e-01\n'

In [126]:
get_csv_file.readlines()

[]

In [127]:
get_csv_file.close()

In [129]:
get_csv_file2 = np.loadtxt(file2)
get_csv_file2

ValueError: could not convert string '1.842995381228673679e-02,1.672713832088749131e-01,5.245808899561253957e-01,9.567306592828144218e-01 to float64 at row 0, column 1.

In [130]:
get_csv_file = open(file2, 'r')
get_csv_file

<_io.TextIOWrapper name='/Users/damilare/Documents/ingryd/datasets/numpy_data/another_array.csv' mode='r' encoding='UTF-8'>

In [131]:
[data for data in get_csv_file]

['1.842995381228673679e-02,1.672713832088749131e-01,5.245808899561253957e-01,9.567306592828144218e-01\n',
 '8.282089075405481005e-01,5.670513082269779126e-02,5.910405949723169794e-01,9.064210937126564449e-01\n',
 '8.068149984836069377e-01,3.056281348720055746e-01,1.509596063551595924e-01,9.158611103135182452e-01\n']

In [133]:
get_csv_file = open(file2, 'r')
get_csv_file

for data in get_csv_file:
    print(data, '=>', type(data))

1.842995381228673679e-02,1.672713832088749131e-01,5.245808899561253957e-01,9.567306592828144218e-01
 => <class 'str'>
8.282089075405481005e-01,5.670513082269779126e-02,5.910405949723169794e-01,9.064210937126564449e-01
 => <class 'str'>
8.068149984836069377e-01,3.056281348720055746e-01,1.509596063551595924e-01,9.158611103135182452e-01
 => <class 'str'>


In [134]:
get_csv_file2 = np.loadtxt(file2, delimiter=',')
get_csv_file2

array([[0.01842995, 0.16727138, 0.52458089, 0.95673066],
       [0.82820891, 0.05670513, 0.59104059, 0.90642109],
       [0.806815  , 0.30562813, 0.15095961, 0.91586111]])

### Array Slicing

The following notes should be remembered when working with NP array slicing

- The colon works with arrays just like with Lists, however, we're dealing with at least 1d array.
- Select all rows from a to b and all columns from c to d for a 2d array 'arry' with arry[a:b, c:d].
- Select every row in a dimension with : e.g. arry[a:b, :].
- Select all rows up to b with arry[:b, :].
- Select all rows after and including row a with arry[a:]
- A second colon can be used to go by increment/step e.g. arry[a:b:i, :] or arry[a:b:(-1), :] for a
-ve slicing or to go in the reverse direction.

In [145]:
# ex

arry1 = np.array([
    [
        ['John', 'Doe', 'Tobe'],
        ['Franca', 'Funsho', 'Gideon'],
        ['Ire', 'Yemi', 'Wakil']
    ],
    [
        ['Dara', 'Joe', 'Dona'],
        ['Feranmi', 'Abubakar', 'Sulaimon'],
        ['Franklin', 'Bola', 'Peter']
    ],
    [
        ['Rasheed', 'Semande', 'Caleb'],
        ['Tunde', 'Timson', 'Kunle'],
        ['Joan', 'Jamiu', 'Patrick']
    ]
    
])

arry1

array([[['John', 'Doe', 'Tobe'],
        ['Franca', 'Funsho', 'Gideon'],
        ['Ire', 'Yemi', 'Wakil']],

       [['Dara', 'Joe', 'Dona'],
        ['Feranmi', 'Abubakar', 'Sulaimon'],
        ['Franklin', 'Bola', 'Peter']],

       [['Rasheed', 'Semande', 'Caleb'],
        ['Tunde', 'Timson', 'Kunle'],
        ['Joan', 'Jamiu', 'Patrick']]], dtype='<U8')

In [136]:
arry1.shape

(3, 3, 3)

In [137]:
arry1.size

27

In [138]:
arry1.ndim

3

In [139]:
# copy the array
arry2 = arry1[:, :,0].copy()
arry2

array([['John', 'Franca', 'Ire'],
       ['Dara', 'Feranmi', 'Franklin'],
       ['Rasheed', 'Tunde', 'Joan']], dtype='<U8')

In [ ]:
# what did we copy?
'''
loop thru the rows, go thru the columns  
'''

In [141]:
arry1[0]

array([['John', 'Doe', 'Tobe'],
       ['Franca', 'Funsho', 'Gideon'],
       ['Ire', 'Yemi', 'Wakil']], dtype='<U8')

In [143]:
arry1[1]

array([['Dara', 'Joe', 'Dona'],
       ['Feranmi', 'Abubakar', 'Sulaimon'],
       ['Franklin', 'Bola', 'Peter']], dtype='<U8')

In [144]:
arry1[2]

array([['Rasheed', 'Semande', 'Caleb'],
       ['Tunde', 'Timson', 'Kunle'],
       ['Joan', 'Jamiu', 'Patrick']], dtype='<U8')

### Wk7_1.3 - Slicing & Indexing Cont

In [146]:
arry1[:2]

array([[['John', 'Doe', 'Tobe'],
        ['Franca', 'Funsho', 'Gideon'],
        ['Ire', 'Yemi', 'Wakil']],

       [['Dara', 'Joe', 'Dona'],
        ['Feranmi', 'Abubakar', 'Sulaimon'],
        ['Franklin', 'Bola', 'Peter']]], dtype='<U8')

In [147]:
arry1[:2, :2]

array([[['John', 'Doe', 'Tobe'],
        ['Franca', 'Funsho', 'Gideon']],

       [['Dara', 'Joe', 'Dona'],
        ['Feranmi', 'Abubakar', 'Sulaimon']]], dtype='<U8')

In [148]:
arry1[:2, :2, :2]

array([[['John', 'Doe'],
        ['Franca', 'Funsho']],

       [['Dara', 'Joe'],
        ['Feranmi', 'Abubakar']]], dtype='<U8')

In [149]:
arry1[:0, :1, :2]

array([], shape=(0, 1, 2), dtype='<U8')

In [150]:
arry1[0:, :1, :2]

array([[['John', 'Doe']],

       [['Dara', 'Joe']],

       [['Rasheed', 'Semande']]], dtype='<U8')

In [151]:
arry1[::-1, :]

array([[['Rasheed', 'Semande', 'Caleb'],
        ['Tunde', 'Timson', 'Kunle'],
        ['Joan', 'Jamiu', 'Patrick']],

       [['Dara', 'Joe', 'Dona'],
        ['Feranmi', 'Abubakar', 'Sulaimon'],
        ['Franklin', 'Bola', 'Peter']],

       [['John', 'Doe', 'Tobe'],
        ['Franca', 'Funsho', 'Gideon'],
        ['Ire', 'Yemi', 'Wakil']]], dtype='<U8')

In [152]:
arry1[::-1, :2]

array([[['Rasheed', 'Semande', 'Caleb'],
        ['Tunde', 'Timson', 'Kunle']],

       [['Dara', 'Joe', 'Dona'],
        ['Feranmi', 'Abubakar', 'Sulaimon']],

       [['John', 'Doe', 'Tobe'],
        ['Franca', 'Funsho', 'Gideon']]], dtype='<U8')

### Advanced Indexing

In [153]:
arry1 # this returns the whole array

array([[['John', 'Doe', 'Tobe'],
        ['Franca', 'Funsho', 'Gideon'],
        ['Ire', 'Yemi', 'Wakil']],

       [['Dara', 'Joe', 'Dona'],
        ['Feranmi', 'Abubakar', 'Sulaimon'],
        ['Franklin', 'Bola', 'Peter']],

       [['Rasheed', 'Semande', 'Caleb'],
        ['Tunde', 'Timson', 'Kunle'],
        ['Joan', 'Jamiu', 'Patrick']]], dtype='<U8')

In [154]:
# get all the data that are not Caleb
print(arry1[arry1 != 'Caleb'])

['John' 'Doe' 'Tobe' 'Franca' 'Funsho' 'Gideon' 'Ire' 'Yemi' 'Wakil'
 'Dara' 'Joe' 'Dona' 'Feranmi' 'Abubakar' 'Sulaimon' 'Franklin' 'Bola'
 'Peter' 'Rasheed' 'Semande' 'Tunde' 'Timson' 'Kunle' 'Joan' 'Jamiu'
 'Patrick']


In [155]:
print(arry1 != 'Caleb') # this returned a list of lists

[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True False]
  [ True  True  True]
  [ True  True  True]]]


In [156]:
arry1 != 'Caleb' # this returned an array of list of lists

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True, False],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [169]:
# get the data via an array of index

# Row indices
idx0 = np.array([
            [
                [0,0],[0,0]
            ], 
            [
                [2,2], [2,2]
            ]
        ])
idx0

array([[[0, 0],
        [0, 0]],

       [[2, 2],
        [2, 2]]])

In [170]:
# Column indices
idx1 = np.array([
            [
                [0,2],[0,2]
            ],
            [
                [0,2],[0,2]
            ]
        ])
idx1

array([[[0, 2],
        [0, 2]],

       [[0, 2],
        [0, 2]]])

In [171]:
# Depth indices
idx2 = np.array([
            [
                [0,0],[2,2]
            ],
            [
                [0,0],[2,2]
            ]
        ])
idx2

array([[[0, 0],
        [2, 2]],

       [[0, 0],
        [2, 2]]])

In [192]:
arry1[idx0, idx1, idx2]

array([[['John', 'Ire'],
        ['Tobe', 'Wakil']],

       [['Rasheed', 'Joan'],
        ['Caleb', 'Patrick']]], dtype='<U8')

In [168]:
arry1

array([[['John', 'Doe', 'Tobe'],
        ['Franca', 'Funsho', 'Gideon'],
        ['Ire', 'Yemi', 'Wakil']],

       [['Dara', 'Joe', 'Dona'],
        ['Feranmi', 'Abubakar', 'Sulaimon'],
        ['Franklin', 'Bola', 'Peter']],

       [['Rasheed', 'Semande', 'Caleb'],
        ['Tunde', 'Timson', 'Kunle'],
        ['Joan', 'Jamiu', 'Patrick']]], dtype='<U8')

In [185]:
arry1.ndim

3

### Array Expansion

In [195]:
# you can use the concatenate mtd to join two arrays together
arry1

array([[['John', 'Doe', 'Tobe'],
        ['Franca', 'Funsho', 'Gideon'],
        ['Ire', 'Yemi', 'Wakil']],

       [['Dara', 'Joe', 'Dona'],
        ['Feranmi', 'Abubakar', 'Sulaimon'],
        ['Franklin', 'Bola', 'Peter']],

       [['Rasheed', 'Semande', 'Caleb'],
        ['Tunde', 'Timson', 'Kunle'],
        ['Joan', 'Jamiu', 'Patrick']]], dtype='<U8')

In [199]:
new_arry1 = arry1[0]
new_arry1

array([['John', 'Doe', 'Tobe'],
       ['Franca', 'Funsho', 'Gideon'],
       ['Ire', 'Yemi', 'Wakil']], dtype='<U8')

In [200]:
new_arry1.ndim

2

In [202]:
new_arry2 = arry1[1]
new_arry2

array([['Dara', 'Joe', 'Dona'],
       ['Feranmi', 'Abubakar', 'Sulaimon'],
       ['Franklin', 'Bola', 'Peter']], dtype='<U8')

In [203]:
new_arry2.shape

(3, 3)

In [204]:
new_arry1.shape

(3, 3)

In [205]:
joined_arrys = np.concatenate((new_arry1, new_arry2))
joined_arrys

array([['John', 'Doe', 'Tobe'],
       ['Franca', 'Funsho', 'Gideon'],
       ['Ire', 'Yemi', 'Wakil'],
       ['Dara', 'Joe', 'Dona'],
       ['Feranmi', 'Abubakar', 'Sulaimon'],
       ['Franklin', 'Bola', 'Peter']], dtype='<U8')

In [207]:
joined_arrys.shape

(6, 3)

In [208]:
joined_arrys.ndim

2

In [215]:
# the syntax for the concatenate is np.concatenate((arr1, arr2), axis=n) where n = the dimensions
first_arry = np.array([[1,3], [5,7]])
sec_arry = np.array([[2,4]]) # the extra sq brac makes it a 2d

first_arry.shape

(2, 2)

In [216]:
sec_arry.shape

(1, 2)

In [217]:
print(f'first array dim => {first_arry.ndim}')
print(f'second array dim => {sec_arry.ndim}')

first array dim => 2
second array dim => 2


In [218]:
combined_arrys = np.concatenate((first_arry, sec_arry))
combined_arrys

array([[1, 3],
       [5, 7],
       [2, 4]])

In [220]:
combined_arrys_axis_0 = np.concatenate((first_arry, sec_arry), axis=0)
combined_arrys_axis_0 # the axis are zero by default

array([[1, 3],
       [5, 7],
       [2, 4]])

In [221]:
combined_arrys_axis_1 = np.concatenate((first_arry, sec_arry), axis=1)
combined_arrys_axis_1

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [223]:
# Ex2 on Concatenation
xarry = np.array([
    [
        [0,1],
        [2,3]
    ],
    [
        [4,5],
        [6,7]
    ]
])


yarry = np.array([
    [
        [10,11],
        [12,13]
    ],
    [
        [14,15],
        [16,17]
    ]
])

print('Getting the arrays...\n')
print('X ARRAYS')
print(xarry)
print('\nY ARRAYS')
print(yarry)

Getting the arrays...

X ARRAYS
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

Y ARRAYS
[[[10 11]
  [12 13]]

 [[14 15]
  [16 17]]]


In [224]:
print(f'x array dim => {xarry.ndim}')
print(f'y array dim => {yarry.ndim}')

x array dim => 3
y array dim => 3


In [225]:
print(f'x array shapes => {xarry.shape}')
print(f'y array shapes => {yarry.shape}')

x array shapes => (2, 2, 2)
y array shapes => (2, 2, 2)


In [226]:
# Start with axis 0
axes0arrys = np.concatenate((xarry, yarry), 0) # putting the arg 0 == saying axis = 0
axes0arrys

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17]]])

In [227]:
# Try for axis = 1
axes1arrys = np.concatenate((xarry, yarry), 1) # putting the arg 1 == saying axis = 1
axes1arrys

array([[[ 0,  1],
        [ 2,  3],
        [10, 11],
        [12, 13]],

       [[ 4,  5],
        [ 6,  7],
        [14, 15],
        [16, 17]]])

In [230]:
# ([x0,x1],[y0,y1]) => axis = 0
# ([x0,y0], [x1,y1]) => axis = 1

In [228]:
print(f'axis 0 array shapes => {axes0arrys.shape}')
print(f'axis 1 array shapes => {axes1arrys.shape}')

axis 0 array shapes => (4, 2, 2)
axis 1 array shapes => (2, 4, 2)


In [229]:
print(f'axis 0 array dim => {axes0arrys.ndim}')
print(f'axis 1 array dim => {axes1arrys.ndim}')

axis 0 array dim => 3
axis 1 array dim => 3


In [231]:
# Try fo axis = 2
axes2arrys = np.concatenate((xarry, yarry), axis=2) # putting the arg 2 == saying axis = 2
axes2arrys

array([[[ 0,  1, 10, 11],
        [ 2,  3, 12, 13]],

       [[ 4,  5, 14, 15],
        [ 6,  7, 16, 17]]])

In [232]:
axes0arrys # to compare with the default concatenation

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17]]])

In [233]:
axes2arrys.shape

(2, 2, 4)

In [234]:
# Try fo axis = None
axes2arrys = np.concatenate((xarry, yarry), axis= None) # putting the arg None == saying axis = None
axes2arrys # this flattens the array.

array([ 0,  1,  2,  3,  4,  5,  6,  7, 10, 11, 12, 13, 14, 15, 16, 17])